[2025-04-05T04:50:00.678+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T04:50:00.742+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_constructors scheduled__2025-04-02T00:00:00+00:00 [queued]>
[2025-04-05T04:50:00.772+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_constructors scheduled__2025-04-02T00:00:00+00:00 [queued]>
[2025-04-05T04:50:00.777+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-05T04:50:00.826+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_constructors> on 2025-04-02 00:00:00+00:00
[2025-04-05T04:50:00.855+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=461) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T04:50:00.864+0000] {standard_task_runner.py:63} INFO - Started process 488 to run task
[2025-04-05T04:50:00.870+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform.transform_dim_constructors', 'scheduled__2025-04-02T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmpe1l485x8']
[2025-04-05T04:50:00.879+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask transform.transform_dim_constructors
[2025-04-05T04:50:01.049+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform.transform_dim_constructors scheduled__2025-04-02T00:00:00+00:00 [running]> on host 7b82c2aa8826
[2025-04-05T04:50:01.352+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform.transform_dim_constructors' AIRFLOW_CTX_EXECUTION_DATE='2025-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-02T00:00:00+00:00'
[2025-04-05T04:50:01.357+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T04:50:01.606+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-05T04:50:01.665+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-05T04:50:01.731+0000] {logging_mixin.py:188} INFO - Lỗi khi insert dữ liệu: duplicate key value violates unique constraint "dim_constructors_pkey"
DETAIL:  Key (constructorid)=(1) already exists.
[2025-04-05T04:50:01.737+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T04:50:01.740+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T04:50:01.790+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=transform.transform_dim_constructors, run_id=scheduled__2025-04-02T00:00:00+00:00, execution_date=20250402T000000, start_date=20250405T045000, end_date=20250405T045001
[2025-04-05T04:50:01.871+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T04:50:01.968+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T04:50:01.975+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T04:54:06.174+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T04:54:06.303+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_constructors scheduled__2025-04-02T00:00:00+00:00 [queued]>
[2025-04-05T04:54:06.323+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_constructors scheduled__2025-04-02T00:00:00+00:00 [queued]>
[2025-04-05T04:54:06.324+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-05T04:54:06.376+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_constructors> on 2025-04-02 00:00:00+00:00
[2025-04-05T04:54:06.415+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=432) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T04:54:06.420+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform.transform_dim_constructors', 'scheduled__2025-04-02T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmpfg123pnp']
[2025-04-05T04:54:06.447+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask transform.transform_dim_constructors
[2025-04-05T04:54:06.437+0000] {standard_task_runner.py:63} INFO - Started process 481 to run task
[2025-04-05T04:54:06.607+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform.transform_dim_constructors scheduled__2025-04-02T00:00:00+00:00 [running]> on host 4766eee3ca7d
[2025-04-05T04:54:07.028+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform.transform_dim_constructors' AIRFLOW_CTX_EXECUTION_DATE='2025-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-02T00:00:00+00:00'
[2025-04-05T04:54:07.046+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T04:54:07.215+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T04:54:07.234+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/transform_dim_constructors.py", line 27, in transform_dim_constructors
    warehouse_operator.create_table(create_table_qr)
  File "/opt/airflow/dags/postgresql_operator.py", line 10, in create_table
    conn = pg_hook.get_conn()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 145, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2025-04-05T04:54:07.308+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=e_commerce_dw_etl, task_id=transform.transform_dim_constructors, run_id=scheduled__2025-04-02T00:00:00+00:00, execution_date=20250402T000000, start_date=20250405T045406, end_date=20250405T045407
[2025-04-05T04:54:07.386+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 37 for task transform.transform_dim_constructors (The conn_id `postgres_default` isn't defined; 481)
[2025-04-05T04:54:07.447+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-05T04:54:07.495+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T04:54:07.511+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
