[2025-04-05T04:50:04.337+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T04:50:04.417+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_seasons scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T04:50:04.461+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_seasons scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T04:50:04.462+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-05T04:50:04.491+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_seasons> on 2025-04-04 00:00:00+00:00
[2025-04-05T04:50:04.509+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=504) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T04:50:04.511+0000] {standard_task_runner.py:63} INFO - Started process 534 to run task
[2025-04-05T04:50:04.514+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform.transform_dim_seasons', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmp9dl5ades']
[2025-04-05T04:50:04.519+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask transform.transform_dim_seasons
[2025-04-05T04:50:04.629+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform.transform_dim_seasons scheduled__2025-04-04T00:00:00+00:00 [running]> on host 7b82c2aa8826
[2025-04-05T04:50:04.940+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform.transform_dim_seasons' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-05T04:50:04.943+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T04:50:05.078+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-05T04:50:05.145+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-05T04:50:05.170+0000] {logging_mixin.py:188} INFO - Lỗi khi insert dữ liệu: duplicate key value violates unique constraint "dim_seasons_pkey"
DETAIL:  Key (seasonid)=(2009) already exists.
[2025-04-05T04:50:05.184+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T04:50:05.198+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T04:50:05.238+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=transform.transform_dim_seasons, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250405T045004, end_date=20250405T045005
[2025-04-05T04:50:05.310+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T04:50:05.404+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T04:50:05.422+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T04:54:09.164+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T04:54:09.235+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_seasons scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T04:54:09.250+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_seasons scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T04:54:09.251+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-05T04:54:09.274+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_seasons> on 2025-04-04 00:00:00+00:00
[2025-04-05T04:54:09.289+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=514) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T04:54:09.289+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform.transform_dim_seasons', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmp6u6ty1jw']
[2025-04-05T04:54:09.291+0000] {standard_task_runner.py:63} INFO - Started process 541 to run task
[2025-04-05T04:54:09.292+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask transform.transform_dim_seasons
[2025-04-05T04:54:09.368+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform.transform_dim_seasons scheduled__2025-04-04T00:00:00+00:00 [running]> on host 4766eee3ca7d
[2025-04-05T04:54:09.487+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform.transform_dim_seasons' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-05T04:54:09.489+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T04:54:09.540+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T04:54:09.549+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/transform_dim_seasons.py", line 30, in transform_dim_seasons
    warehouse_operator.create_table(create_table_qr)
  File "/opt/airflow/dags/postgresql_operator.py", line 10, in create_table
    conn = pg_hook.get_conn()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 145, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2025-04-05T04:54:09.558+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=e_commerce_dw_etl, task_id=transform.transform_dim_seasons, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250405T045409, end_date=20250405T045409
[2025-04-05T04:54:09.569+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 57 for task transform.transform_dim_seasons (The conn_id `postgres_default` isn't defined; 541)
[2025-04-05T04:54:09.591+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-05T04:54:09.608+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T04:54:09.610+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
