[2025-04-05T04:53:59.493+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T04:53:59.528+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_circuits manual__2025-04-05T04:53:55.493484+00:00 [queued]>
[2025-04-05T04:53:59.539+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_circuits manual__2025-04-05T04:53:55.493484+00:00 [queued]>
[2025-04-05T04:53:59.540+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-05T04:53:59.556+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_circuits> on 2025-04-05 04:53:55.493484+00:00
[2025-04-05T04:53:59.571+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform.transform_dim_circuits', 'manual__2025-04-05T04:53:55.493484+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmplsoakete']
[2025-04-05T04:53:59.574+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask transform.transform_dim_circuits
[2025-04-05T04:53:59.575+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=335) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T04:53:59.576+0000] {standard_task_runner.py:63} INFO - Started process 348 to run task
[2025-04-05T04:53:59.628+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform.transform_dim_circuits manual__2025-04-05T04:53:55.493484+00:00 [running]> on host 4766eee3ca7d
[2025-04-05T04:53:59.735+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform.transform_dim_circuits' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T04:53:55.493484+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-05T04:53:55.493484+00:00'
[2025-04-05T04:53:59.737+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T04:53:59.751+0000] {logging_mixin.py:188} INFO - /opt/***/dataset
[2025-04-05T04:53:59.760+0000] {logging_mixin.py:188} INFO - đã đọc được circuits
[2025-04-05T04:53:59.762+0000] {logging_mixin.py:188} INFO - tạo dc postgres
[2025-04-05T04:53:59.770+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T04:53:59.779+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/transform_dim_circuits.py", line 35, in transform_dim_circuits
    warehouse_operator.create_table(create_table_qr)
  File "/opt/airflow/dags/postgresql_operator.py", line 10, in create_table
    conn = pg_hook.get_conn()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 145, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2025-04-05T04:53:59.788+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=e_commerce_dw_etl, task_id=transform.transform_dim_circuits, run_id=manual__2025-04-05T04:53:55.493484+00:00, execution_date=20250405T045355, start_date=20250405T045359, end_date=20250405T045359
[2025-04-05T04:53:59.798+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task transform.transform_dim_circuits (The conn_id `postgres_default` isn't defined; 348)
[2025-04-05T04:53:59.834+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-05T04:53:59.843+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
