[2025-04-05T04:50:03.963+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T04:50:04.111+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_circuits scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-05T04:50:04.137+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_circuits scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-05T04:50:04.143+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-05T04:50:04.193+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_circuits> on 2025-04-03 00:00:00+00:00
[2025-04-05T04:50:04.235+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform.transform_dim_circuits', 'scheduled__2025-04-03T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmpo1cpk_wk']
[2025-04-05T04:50:04.239+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask transform.transform_dim_circuits
[2025-04-05T04:50:04.235+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=494) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T04:50:04.244+0000] {standard_task_runner.py:63} INFO - Started process 528 to run task
[2025-04-05T04:50:04.424+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform.transform_dim_circuits scheduled__2025-04-03T00:00:00+00:00 [running]> on host 7b82c2aa8826
[2025-04-05T04:50:04.613+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform.transform_dim_circuits' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-03T00:00:00+00:00'
[2025-04-05T04:50:04.617+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T04:50:04.661+0000] {logging_mixin.py:188} INFO - /opt/***/dataset
[2025-04-05T04:50:04.696+0000] {logging_mixin.py:188} INFO - đã đọc được circuits
[2025-04-05T04:50:04.709+0000] {logging_mixin.py:188} INFO - tạo dc postgres
[2025-04-05T04:50:04.742+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-05T04:50:04.770+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-05T04:50:04.807+0000] {logging_mixin.py:188} INFO - Lỗi khi insert dữ liệu: duplicate key value violates unique constraint "dim_circuits_pkey"
DETAIL:  Key (circuitid)=(1) already exists.
[2025-04-05T04:50:04.824+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T04:50:04.825+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T04:50:04.848+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=transform.transform_dim_circuits, run_id=scheduled__2025-04-03T00:00:00+00:00, execution_date=20250403T000000, start_date=20250405T045004, end_date=20250405T045004
[2025-04-05T04:50:04.984+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T04:50:05.043+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-05T04:50:05.047+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T04:54:08.647+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T04:54:08.692+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_circuits scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-05T04:54:08.706+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_circuits scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-05T04:54:08.707+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-05T04:54:08.728+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_circuits> on 2025-04-03 00:00:00+00:00
[2025-04-05T04:54:08.741+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=491) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T04:54:08.743+0000] {standard_task_runner.py:63} INFO - Started process 531 to run task
[2025-04-05T04:54:08.742+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform.transform_dim_circuits', 'scheduled__2025-04-03T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmps65vcxy5']
[2025-04-05T04:54:08.745+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask transform.transform_dim_circuits
[2025-04-05T04:54:08.856+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform.transform_dim_circuits scheduled__2025-04-03T00:00:00+00:00 [running]> on host 4766eee3ca7d
[2025-04-05T04:54:09.053+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform.transform_dim_circuits' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-03T00:00:00+00:00'
[2025-04-05T04:54:09.065+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T04:54:09.086+0000] {logging_mixin.py:188} INFO - /opt/***/dataset
[2025-04-05T04:54:09.105+0000] {logging_mixin.py:188} INFO - đã đọc được circuits
[2025-04-05T04:54:09.111+0000] {logging_mixin.py:188} INFO - tạo dc postgres
[2025-04-05T04:54:09.136+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T04:54:09.153+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/transform_dim_circuits.py", line 35, in transform_dim_circuits
    warehouse_operator.create_table(create_table_qr)
  File "/opt/airflow/dags/postgresql_operator.py", line 10, in create_table
    conn = pg_hook.get_conn()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 145, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2025-04-05T04:54:09.171+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=e_commerce_dw_etl, task_id=transform.transform_dim_circuits, run_id=scheduled__2025-04-03T00:00:00+00:00, execution_date=20250403T000000, start_date=20250405T045408, end_date=20250405T045409
[2025-04-05T04:54:09.191+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 49 for task transform.transform_dim_circuits (The conn_id `postgres_default` isn't defined; 531)
[2025-04-05T04:54:09.251+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-05T04:54:09.277+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T04:54:09.279+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
