[2025-04-08T09:27:42.868+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-08T09:27:42.956+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: formula1-etl-pipeline.transform.transform_dim_constructors scheduled__2025-04-07T00:00:00+00:00 [queued]>
[2025-04-08T09:27:42.981+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: formula1-etl-pipeline.transform.transform_dim_constructors scheduled__2025-04-07T00:00:00+00:00 [queued]>
[2025-04-08T09:27:42.983+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-08T09:27:43.023+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_constructors> on 2025-04-07 00:00:00+00:00
[2025-04-08T09:27:43.070+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=781) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T09:27:43.073+0000] {standard_task_runner.py:63} INFO - Started process 805 to run task
[2025-04-08T09:27:43.062+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'formula1-etl-pipeline', 'transform.transform_dim_constructors', 'scheduled__2025-04-07T00:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmp6v10nrhb']
[2025-04-08T09:27:43.119+0000] {standard_task_runner.py:91} INFO - Job 62: Subtask transform.transform_dim_constructors
[2025-04-08T09:27:43.230+0000] {task_command.py:426} INFO - Running <TaskInstance: formula1-etl-pipeline.transform.transform_dim_constructors scheduled__2025-04-07T00:00:00+00:00 [running]> on host 1c2d39091a25
[2025-04-08T09:27:43.535+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='formula1-etl-pipeline' AIRFLOW_CTX_TASK_ID='transform.transform_dim_constructors' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-07T00:00:00+00:00'
[2025-04-08T09:27:43.548+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-08T09:27:43.698+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-08T09:27:43.709+0000] {logging_mixin.py:188} INFO - Đã tạo bảng thành công.
[2025-04-08T09:27:43.728+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-08T09:27:43.779+0000] {logging_mixin.py:188} INFO - Lỗi khi insert dữ liệu: duplicate key value violates unique constraint "dim_constructors_pkey"
DETAIL:  Key (constructorid)=(1) already exists.
[2025-04-08T09:27:43.786+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-08T09:27:43.787+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/transform_dim_constructors.py", line 34, in transform_dim_constructors
    warehouse_operator.insert_table(insert_table_querry, dim_constructors_df)
  File "/opt/airflow/dags/postgresql_operator.py", line 35, in insert_table
    cursor.executemany(query, values)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dim_constructors_pkey"
DETAIL:  Key (constructorid)=(1) already exists.

[2025-04-08T09:27:43.842+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=formula1-etl-pipeline, task_id=transform.transform_dim_constructors, run_id=scheduled__2025-04-07T00:00:00+00:00, execution_date=20250407T000000, start_date=20250408T092742, end_date=20250408T092743
[2025-04-08T09:27:43.877+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 62 for task transform.transform_dim_constructors (duplicate key value violates unique constraint "dim_constructors_pkey"
DETAIL:  Key (constructorid)=(1) already exists.
; 805)
[2025-04-08T09:27:43.946+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-08T09:27:44.001+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T09:27:44.020+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
