[2025-04-04T18:20:55.273+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-04T18:20:55.313+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_races manual__2025-04-04T18:20:50.735802+00:00 [queued]>
[2025-04-04T18:20:55.323+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_races manual__2025-04-04T18:20:50.735802+00:00 [queued]>
[2025-04-04T18:20:55.324+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-04T18:20:55.344+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_races> on 2025-04-04 18:20:50.735802+00:00
[2025-04-04T18:20:55.355+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform.transform_dim_races', 'manual__2025-04-04T18:20:50.735802+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmptiq35nbo']
[2025-04-04T18:20:55.357+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask transform.transform_dim_races
[2025-04-04T18:20:55.359+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=459) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-04T18:20:55.360+0000] {standard_task_runner.py:63} INFO - Started process 474 to run task
[2025-04-04T18:20:55.414+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform.transform_dim_races manual__2025-04-04T18:20:50.735802+00:00 [running]> on host 729d59a438a8
[2025-04-04T18:20:55.505+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform.transform_dim_races' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T18:20:50.735802+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-04T18:20:50.735802+00:00'
[2025-04-04T18:20:55.507+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-04T18:20:55.586+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-04T18:20:55.601+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-04T18:20:55.602+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/transform_dim_races.py", line 35, in transform_dim_races
    warehouse_operator.create_table(create_table_qr)
  File "/opt/airflow/dags/postgresql_operator.py", line 12, in create_table
    cursor.execute(query)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(dim_races, 2200) already exists.

[2025-04-04T18:20:55.619+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=e_commerce_dw_etl, task_id=transform.transform_dim_races, run_id=manual__2025-04-04T18:20:50.735802+00:00, execution_date=20250404T182050, start_date=20250404T182055, end_date=20250404T182055
[2025-04-04T18:20:55.672+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task transform.transform_dim_races (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(dim_races, 2200) already exists.
; 474)
[2025-04-04T18:20:55.735+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-04T18:20:55.763+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-04T18:20:55.766+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
