[2025-04-05T04:50:04.047+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T04:50:04.186+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_drivers scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-05T04:50:04.210+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_drivers scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-05T04:50:04.230+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-05T04:50:04.269+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_drivers> on 2025-04-03 00:00:00+00:00
[2025-04-05T04:50:04.286+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=497) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T04:50:04.286+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform.transform_dim_drivers', 'scheduled__2025-04-03T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmpubdpjm59']
[2025-04-05T04:50:04.290+0000] {standard_task_runner.py:63} INFO - Started process 529 to run task
[2025-04-05T04:50:04.290+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask transform.transform_dim_drivers
[2025-04-05T04:50:04.406+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform.transform_dim_drivers scheduled__2025-04-03T00:00:00+00:00 [running]> on host 7b82c2aa8826
[2025-04-05T04:50:04.575+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform.transform_dim_drivers' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-03T00:00:00+00:00'
[2025-04-05T04:50:04.580+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T04:50:04.686+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-05T04:50:04.739+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-05T04:50:04.864+0000] {logging_mixin.py:188} INFO - Lỗi khi insert dữ liệu: duplicate key value violates unique constraint "dim_drivers_pkey"
DETAIL:  Key (driverid)=(1) already exists.
[2025-04-05T04:50:04.869+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T04:50:04.881+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T04:50:04.913+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=transform.transform_dim_drivers, run_id=scheduled__2025-04-03T00:00:00+00:00, execution_date=20250403T000000, start_date=20250405T045004, end_date=20250405T045004
[2025-04-05T04:50:05.005+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T04:50:05.035+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T04:54:06.336+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T04:54:06.463+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_drivers scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-05T04:54:06.508+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_drivers scheduled__2025-04-03T00:00:00+00:00 [queued]>
[2025-04-05T04:54:06.510+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-05T04:54:06.560+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_drivers> on 2025-04-03 00:00:00+00:00
[2025-04-05T04:54:06.579+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=447) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T04:54:06.581+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform.transform_dim_drivers', 'scheduled__2025-04-03T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmp42u1lfco']
[2025-04-05T04:54:06.595+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask transform.transform_dim_drivers
[2025-04-05T04:54:06.595+0000] {standard_task_runner.py:63} INFO - Started process 484 to run task
[2025-04-05T04:54:06.816+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform.transform_dim_drivers scheduled__2025-04-03T00:00:00+00:00 [running]> on host 4766eee3ca7d
[2025-04-05T04:54:07.172+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform.transform_dim_drivers' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-03T00:00:00+00:00'
[2025-04-05T04:54:07.177+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T04:54:07.368+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T04:54:07.442+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/transform_dim_drivers.py", line 39, in transform_dim_drivers
    warehouse_operator.create_table(create_table_qr)
  File "/opt/airflow/dags/postgresql_operator.py", line 10, in create_table
    conn = pg_hook.get_conn()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 145, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2025-04-05T04:54:07.480+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=e_commerce_dw_etl, task_id=transform.transform_dim_drivers, run_id=scheduled__2025-04-03T00:00:00+00:00, execution_date=20250403T000000, start_date=20250405T045406, end_date=20250405T045407
[2025-04-05T04:54:07.548+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 41 for task transform.transform_dim_drivers (The conn_id `postgres_default` isn't defined; 484)
[2025-04-05T04:54:07.605+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-05T04:54:07.736+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T04:54:07.770+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
