[2025-04-08T09:08:21.569+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-08T09:08:21.632+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: formula1-etl-pipeline.extract.extract_and_load_to_staging manual__2025-04-08T09:08:20.089813+00:00 [queued]>
[2025-04-08T09:08:21.653+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: formula1-etl-pipeline.extract.extract_and_load_to_staging manual__2025-04-08T09:08:20.089813+00:00 [queued]>
[2025-04-08T09:08:21.654+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-08T09:08:21.807+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2025-04-08 09:08:20.089813+00:00
[2025-04-08T09:08:21.824+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'formula1-etl-pipeline', 'extract.extract_and_load_to_staging', 'manual__2025-04-08T09:08:20.089813+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmpogm98eqj']
[2025-04-08T09:08:21.829+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask extract.extract_and_load_to_staging
[2025-04-08T09:08:21.831+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=478) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T09:08:21.835+0000] {standard_task_runner.py:63} INFO - Started process 496 to run task
[2025-04-08T09:08:21.935+0000] {task_command.py:426} INFO - Running <TaskInstance: formula1-etl-pipeline.extract.extract_and_load_to_staging manual__2025-04-08T09:08:20.089813+00:00 [running]> on host bbffae879616
[2025-04-08T09:08:22.131+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='formula1-etl-pipeline' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T09:08:20.089813+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-08T09:08:20.089813+00:00'
[2025-04-08T09:08:22.132+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-08T09:08:24.806+0000] {logging_mixin.py:188} WARNING -   0%|          | 0.00/6.28M [00:00<?, ?B/s]
[2025-04-08T09:08:25.750+0000] {logging_mixin.py:188} WARNING -  16%|#5        | 1.00M/6.28M [00:00<00:04, 1.11MB/s]
[2025-04-08T09:08:25.887+0000] {logging_mixin.py:188} WARNING -  32%|###1      | 2.00M/6.28M [00:01<00:02, 2.24MB/s]
[2025-04-08T09:08:25.989+0000] {logging_mixin.py:188} WARNING -  48%|####7     | 3.00M/6.28M [00:01<00:00, 3.48MB/s]
[2025-04-08T09:08:26.097+0000] {logging_mixin.py:188} WARNING -  64%|######3   | 4.00M/6.28M [00:01<00:00, 4.66MB/s]
[2025-04-08T09:08:26.202+0000] {logging_mixin.py:188} WARNING -  80%|#######9  | 5.00M/6.28M [00:01<00:00, 5.77MB/s]
[2025-04-08T09:08:26.331+0000] {logging_mixin.py:188} WARNING -  96%|#########5| 6.00M/6.28M [00:01<00:00, 6.40MB/s]
[2025-04-08T09:08:26.369+0000] {logging_mixin.py:188} WARNING - 100%|##########| 6.28M/6.28M [00:01<00:00, 4.22MB/s]
[2025-04-08T09:08:27.679+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-08T09:08:27.680+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_data.py", line 13, in extract_and_load_to_staging
    dataset_path = kagglehub.dataset_download("rohanrao/formula-1-world-championship-1950-2020")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kagglehub/datasets.py", line 35, in dataset_download
    path, _ = registry.dataset_resolver(h, path, force_download=force_download)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kagglehub/registry.py", line 28, in __call__
    return impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kagglehub/resolver.py", line 29, in __call__
    path, version = self._resolve(handle, path, force_download=force_download)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kagglehub/http_resolver.py", line 135, in _resolve
    os.remove(archive_path)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dataset/datasets/rohanrao/formula-1-world-championship-1950-2020/24.archive'
[2025-04-08T09:08:27.694+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=formula1-etl-pipeline, task_id=extract.extract_and_load_to_staging, run_id=manual__2025-04-08T09:08:20.089813+00:00, execution_date=20250408T090820, start_date=20250408T090821, end_date=20250408T090827
[2025-04-08T09:08:27.712+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task extract.extract_and_load_to_staging ([Errno 2] No such file or directory: '/opt/airflow/dataset/datasets/rohanrao/formula-1-world-championship-1950-2020/24.archive'; 496)
[2025-04-08T09:08:27.757+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-08T09:08:27.784+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T09:08:27.790+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
